### ISSUE TITLE
Use SpanStatusFromHTTPStatusCodeAndSpanKind instead of SpanStatusFromHTTPStatusCode

### ISSUE THREAD

**Issue by morigs** [psmarcin/fiber-opentelemetry#36]
It's recommended to use [SpanStatusFromHTTPStatusCodeAndSpanKind](https://github.com/open-telemetry/opentelemetry-go/pull/2339) instead of [SpanStatusFromHTTPStatusCode](https://github.com/psmarcin/fiber-opentelemetry/blob/b7b33cff48fce231bd55f953ac991a0f5a630859/pkg/fiber-otel/middleware.go#L66)

**Comment by psmarcin** [comment]
Hi @morigs thanks so much for pointing this out. I've made that change and it's released now: 
https://github.com/psmarcin/fiber-opentelemetry/releases/tag/v1.0.0
