### ISSUE TITLE
Otelfiber - Any reason to use this repository?

### ISSUE THREAD

**Issue by lucasoares** [psmarcin/fiber-opentelemetry#63]
Hello.

I have a honest question. Is there any reason to use this repository instead of the [contrib/otelfiber](https://github.com/gofiber/contrib/tree/main/otelfiber)?

Shoudn't we just keep one project to build a stronger ecosystem?

Thanks!

**Comment by psmarcin** [comment]
@lucasoares that is excellent question. I didn't know about that library. Back then when I created mine there were zero libs like this. 

Will check if `otelfiber` covers everything, if so then I will archive this one and provide proper description. 

Thanks again for pointing this out :) Will keep you posted.

**Comment by lucasoares** [comment]
Nice! If otelfiber do not covers everything, we could migrate features from here to there..

But it is a library mantained by the fiber/opentelemetry teams themselves.

**Comment by psmarcin** [comment]
Looks like it covers everything. I will update Readme file and archive this repository. Thank you so much @lucasoares for point it out!
